[package]
name = "pp"
version = "0.1.0"
edition = "2024"

[dependencies]
bytes = "1.11.0"
clap = { version = "4.5.53", features = ["derive"] }
docker_credential = "1.3.2"
miette = "7.6.0"
oci-client = "0.15.0"
serde_json = "1.0.145"
tokio = { version = "1.48.0", features = ["full"] }
