[workspace]
authors = ["sophia <scastellarin@openteams.com>"]
channels = ["conda-forge"]
name = "pp"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]
build = "cargo build"
start = "cargo run"
fmt = "cargo fmt --all"
clippy = "cargo clippy --fix"

[dependencies]
rust = ">=1.92.0,<1.93"
