[workspace]
authors = ["sophia <scastellarin@openteams.com>"]
channels = ["conda-forge"]
name = "pp"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]
build = "cargo build"
start = "cargo run"
fmt = "cargo fmt --all"
clippy = "cargo clippy --fix"
start-docker = "docker run -it --rm -d -p 5000:5000 registry:3"

[dependencies]
rust = ">=1.92.0,<1.93"
openssl = ">=3.5.4,<4"
pkg-config = ">=0.29.2,<0.30"
compilers = ">=1.11.0,<2"
oras = ">=1.2.3,<2"
